version: "3.3"
services:
  starport:
    container_name: starport
    image: "starport-gravity/starport"
    ports:
      - "8080:8080"
      - "12345:12345"
      - "26657:26657"
      - "26656:26656"
      - "1317:1317"
      - "9090:9090"
      - "6060:6060"
    networks:
      localnet:
        ipv4_address: 192.168.10.2

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16