name: Build and publish pre-release

# Controls when the action will run. 
on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          scope: starport
          
      - name: Bootstrap
        run: lerna bootstrap --hoist

      - name: Build
        run: lerna run build --scope='{@starport/client-js,@starport/vue,@starport/vuex}'

      - name: Publish
        run: lerna publish --canary --preid beta --dist-tag next --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{secrets.sp_npm_token}}
